"""Command-line interface for running the KeplerMind pipeline."""

from __future__ import annotations

import argparse
import json
from typing import Iterable

from . import build_default_graph
from .state import SessionState


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Execute the KeplerMind agent pipeline and print the generated session report."
        )
    )
    parser.add_argument(
        "--topic",
        help="Optional topic to explore during the session.",
    )
    parser.add_argument(
        "--goal",
        help="Optional learning goal for the session.",
    )
    parser.add_argument(
        "--level",
        dest="level_hint",
        help="Optional proficiency level hint (e.g., beginner, intermediate, advanced).",
    )
    parser.add_argument(
        "--as-json",
        action="store_true",
        help="Output the complete session state as formatted JSON instead of the markdown report.",
    )
    return parser


def main(argv: Iterable[str] | None = None) -> None:
    """Entry point invoked by the ``poetry run keplermind`` command."""

    parser = _build_parser()
    args = parser.parse_args(argv)

    initial_state = SessionState(
        topic=args.topic,
        goal=args.goal,
        level_hint=args.level_hint,
    )

    graph = build_default_graph()
    final_state = graph.run(initial_state)

    if args.as_json:
        print(json.dumps(final_state.to_dict(), indent=2))
    else:
        report = final_state.report or "No report was generated by the agent pipeline."
        print(report)


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    main()
